// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package store

import (
	"errors"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type metadataEntity_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var MetadataEntityBinding = metadataEntity_EntityInfo{
	Entity: objectbox.Entity{
		Id: 1,
	},
	Uid: 7125977000538646976,
}

// MetadataEntity_ contains type-based Property helpers to facilitate some common operations such as Queries.
var MetadataEntity_ = struct {
	Id            *objectbox.PropertyUint64
	SchemaVersion *objectbox.PropertyInt
	SourcePath    *objectbox.PropertyString
	Status        *objectbox.PropertyString
	ErrorText     *objectbox.PropertyString
	StartedAt     *objectbox.PropertyInt64
	CompletedAt   *objectbox.PropertyInt64
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &MetadataEntityBinding.Entity,
		},
	},
	SchemaVersion: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &MetadataEntityBinding.Entity,
		},
	},
	SourcePath: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &MetadataEntityBinding.Entity,
		},
	},
	Status: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &MetadataEntityBinding.Entity,
		},
	},
	ErrorText: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &MetadataEntityBinding.Entity,
		},
	},
	StartedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &MetadataEntityBinding.Entity,
		},
	},
	CompletedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &MetadataEntityBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (metadataEntity_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (metadataEntity_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("MetadataEntity", 1, 7125977000538646976)
	model.Property("Id", 6, 1, 209618578448051984)
	model.PropertyFlags(1)
	model.Property("SchemaVersion", 6, 2, 2348443704100105030)
	model.Property("SourcePath", 9, 3, 4696979830662462292)
	model.PropertyFlags(2048)
	model.PropertyIndex(1, 8508792747737138764)
	model.Property("Status", 9, 4, 8686702516850592564)
	model.PropertyFlags(2048)
	model.PropertyIndex(2, 145975261485266389)
	model.Property("ErrorText", 9, 5, 224521710423946532)
	model.Property("StartedAt", 10, 6, 534355464662901870)
	model.Property("CompletedAt", 10, 7, 1544869711414877580)
	model.EntityLastPropertyId(7, 1544869711414877580)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (metadataEntity_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*MetadataEntity).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (metadataEntity_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*MetadataEntity).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (metadataEntity_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (metadataEntity_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*MetadataEntity)
	var propStartedAt int64
	{
		var err error
		propStartedAt, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.StartedAt)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on MetadataEntity.StartedAt: " + err.Error())
		}
	}

	var propCompletedAt int64
	{
		var err error
		propCompletedAt, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.CompletedAt)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on MetadataEntity.CompletedAt: " + err.Error())
		}
	}

	var offsetSourcePath = fbutils.CreateStringOffset(fbb, obj.SourcePath)
	var offsetStatus = fbutils.CreateStringOffset(fbb, obj.Status)
	var offsetErrorText = fbutils.CreateStringOffset(fbb, obj.ErrorText)

	// build the FlatBuffers object
	fbb.StartObject(7)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetInt64Slot(fbb, 1, int64(obj.SchemaVersion))
	fbutils.SetUOffsetTSlot(fbb, 2, offsetSourcePath)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetStatus)
	fbutils.SetUOffsetTSlot(fbb, 4, offsetErrorText)
	fbutils.SetInt64Slot(fbb, 5, propStartedAt)
	fbutils.SetInt64Slot(fbb, 6, propCompletedAt)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (metadataEntity_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'MetadataEntity' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	propStartedAt, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 14))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on MetadataEntity.StartedAt: " + err.Error())
	}

	propCompletedAt, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 16))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on MetadataEntity.CompletedAt: " + err.Error())
	}

	return &MetadataEntity{
		Id:            propId,
		SchemaVersion: fbutils.GetIntSlot(table, 6),
		SourcePath:    fbutils.GetStringSlot(table, 8),
		Status:        fbutils.GetStringSlot(table, 10),
		ErrorText:     fbutils.GetStringSlot(table, 12),
		StartedAt:     propStartedAt,
		CompletedAt:   propCompletedAt,
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (metadataEntity_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*MetadataEntity, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (metadataEntity_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*MetadataEntity), nil)
	}
	return append(slice.([]*MetadataEntity), object.(*MetadataEntity))
}

// Box provides CRUD access to MetadataEntity objects
type MetadataEntityBox struct {
	*objectbox.Box
}

// BoxForMetadataEntity opens a box of MetadataEntity objects
func BoxForMetadataEntity(ob *objectbox.ObjectBox) *MetadataEntityBox {
	return &MetadataEntityBox{
		Box: ob.InternalBox(1),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the MetadataEntity.Id property on the passed object will be assigned the new ID as well.
func (box *MetadataEntityBox) Put(object *MetadataEntity) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the MetadataEntity.Id property on the passed object will be assigned the new ID as well.
func (box *MetadataEntityBox) Insert(object *MetadataEntity) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *MetadataEntityBox) Update(object *MetadataEntity) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *MetadataEntityBox) PutAsync(object *MetadataEntity) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the MetadataEntity.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the MetadataEntity.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *MetadataEntityBox) PutMany(objects []*MetadataEntity) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *MetadataEntityBox) Get(id uint64) (*MetadataEntity, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*MetadataEntity), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *MetadataEntityBox) GetMany(ids ...uint64) ([]*MetadataEntity, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*MetadataEntity), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *MetadataEntityBox) GetManyExisting(ids ...uint64) ([]*MetadataEntity, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*MetadataEntity), nil
}

// GetAll reads all stored objects
func (box *MetadataEntityBox) GetAll() ([]*MetadataEntity, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*MetadataEntity), nil
}

// Remove deletes a single object
func (box *MetadataEntityBox) Remove(object *MetadataEntity) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *MetadataEntityBox) RemoveMany(objects ...*MetadataEntity) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the MetadataEntity_ struct to create conditions.
// Keep the *MetadataEntityQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *MetadataEntityBox) Query(conditions ...objectbox.Condition) *MetadataEntityQuery {
	return &MetadataEntityQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the MetadataEntity_ struct to create conditions.
// Keep the *MetadataEntityQuery if you intend to execute the query multiple times.
func (box *MetadataEntityBox) QueryOrError(conditions ...objectbox.Condition) (*MetadataEntityQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &MetadataEntityQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See MetadataEntityAsyncBox for more information.
func (box *MetadataEntityBox) Async() *MetadataEntityAsyncBox {
	return &MetadataEntityAsyncBox{AsyncBox: box.Box.Async()}
}

// MetadataEntityAsyncBox provides asynchronous operations on MetadataEntity objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type MetadataEntityAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForMetadataEntity creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use MetadataEntityBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForMetadataEntity(ob *objectbox.ObjectBox, timeoutMs uint64) *MetadataEntityAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 1, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 1: %s" + err.Error())
	}
	return &MetadataEntityAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *MetadataEntityAsyncBox) Put(object *MetadataEntity) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *MetadataEntityAsyncBox) Insert(object *MetadataEntity) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *MetadataEntityAsyncBox) Update(object *MetadataEntity) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *MetadataEntityAsyncBox) Remove(object *MetadataEntity) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all MetadataEntity which Id is either 42 or 47:
//
// box.Query(MetadataEntity_.Id.In(42, 47)).Find()
type MetadataEntityQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *MetadataEntityQuery) Find() ([]*MetadataEntity, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*MetadataEntity), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *MetadataEntityQuery) Offset(offset uint64) *MetadataEntityQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *MetadataEntityQuery) Limit(limit uint64) *MetadataEntityQuery {
	query.Query.Limit(limit)
	return query
}

type fileEntity_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var FileEntityBinding = fileEntity_EntityInfo{
	Entity: objectbox.Entity{
		Id: 2,
	},
	Uid: 2666698206013856343,
}

// FileEntity_ contains type-based Property helpers to facilitate some common operations such as Queries.
var FileEntity_ = struct {
	Id          *objectbox.PropertyUint64
	Path        *objectbox.PropertyString
	Language    *objectbox.PropertyString
	ContentHash *objectbox.PropertyString
	Size        *objectbox.PropertyInt64
	ModifiedAt  *objectbox.PropertyInt64
	IndexedAt   *objectbox.PropertyInt64
	NodeCount   *objectbox.PropertyInt
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &FileEntityBinding.Entity,
		},
	},
	Path: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &FileEntityBinding.Entity,
		},
	},
	Language: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &FileEntityBinding.Entity,
		},
	},
	ContentHash: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &FileEntityBinding.Entity,
		},
	},
	Size: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &FileEntityBinding.Entity,
		},
	},
	ModifiedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &FileEntityBinding.Entity,
		},
	},
	IndexedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &FileEntityBinding.Entity,
		},
	},
	NodeCount: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     8,
			Entity: &FileEntityBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (fileEntity_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (fileEntity_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("FileEntity", 2, 2666698206013856343)
	model.Property("Id", 6, 1, 744142087116066230)
	model.PropertyFlags(1)
	model.Property("Path", 9, 2, 1927260822809403345)
	model.PropertyFlags(2048)
	model.PropertyIndex(3, 3286611023313867966)
	model.Property("Language", 9, 3, 7749746291397620472)
	model.PropertyFlags(2048)
	model.PropertyIndex(4, 3465057872772624453)
	model.Property("ContentHash", 9, 4, 8612910933257049931)
	model.Property("Size", 6, 5, 1584297742594311495)
	model.Property("ModifiedAt", 10, 6, 1698562881254366377)
	model.Property("IndexedAt", 10, 7, 6712063835944434879)
	model.Property("NodeCount", 6, 8, 5388449931475143195)
	model.EntityLastPropertyId(8, 5388449931475143195)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (fileEntity_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*FileEntity).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (fileEntity_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*FileEntity).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (fileEntity_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (fileEntity_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*FileEntity)
	var propModifiedAt int64
	{
		var err error
		propModifiedAt, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.ModifiedAt)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on FileEntity.ModifiedAt: " + err.Error())
		}
	}

	var propIndexedAt int64
	{
		var err error
		propIndexedAt, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.IndexedAt)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on FileEntity.IndexedAt: " + err.Error())
		}
	}

	var offsetPath = fbutils.CreateStringOffset(fbb, obj.Path)
	var offsetLanguage = fbutils.CreateStringOffset(fbb, obj.Language)
	var offsetContentHash = fbutils.CreateStringOffset(fbb, obj.ContentHash)

	// build the FlatBuffers object
	fbb.StartObject(8)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetPath)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetLanguage)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetContentHash)
	fbutils.SetInt64Slot(fbb, 4, obj.Size)
	fbutils.SetInt64Slot(fbb, 5, propModifiedAt)
	fbutils.SetInt64Slot(fbb, 6, propIndexedAt)
	fbutils.SetInt64Slot(fbb, 7, int64(obj.NodeCount))
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (fileEntity_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'FileEntity' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	propModifiedAt, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 14))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on FileEntity.ModifiedAt: " + err.Error())
	}

	propIndexedAt, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 16))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on FileEntity.IndexedAt: " + err.Error())
	}

	return &FileEntity{
		Id:          propId,
		Path:        fbutils.GetStringSlot(table, 6),
		Language:    fbutils.GetStringSlot(table, 8),
		ContentHash: fbutils.GetStringSlot(table, 10),
		Size:        fbutils.GetInt64Slot(table, 12),
		ModifiedAt:  propModifiedAt,
		IndexedAt:   propIndexedAt,
		NodeCount:   fbutils.GetIntSlot(table, 18),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (fileEntity_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*FileEntity, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (fileEntity_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*FileEntity), nil)
	}
	return append(slice.([]*FileEntity), object.(*FileEntity))
}

// Box provides CRUD access to FileEntity objects
type FileEntityBox struct {
	*objectbox.Box
}

// BoxForFileEntity opens a box of FileEntity objects
func BoxForFileEntity(ob *objectbox.ObjectBox) *FileEntityBox {
	return &FileEntityBox{
		Box: ob.InternalBox(2),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the FileEntity.Id property on the passed object will be assigned the new ID as well.
func (box *FileEntityBox) Put(object *FileEntity) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the FileEntity.Id property on the passed object will be assigned the new ID as well.
func (box *FileEntityBox) Insert(object *FileEntity) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *FileEntityBox) Update(object *FileEntity) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *FileEntityBox) PutAsync(object *FileEntity) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the FileEntity.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the FileEntity.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *FileEntityBox) PutMany(objects []*FileEntity) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *FileEntityBox) Get(id uint64) (*FileEntity, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*FileEntity), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *FileEntityBox) GetMany(ids ...uint64) ([]*FileEntity, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*FileEntity), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *FileEntityBox) GetManyExisting(ids ...uint64) ([]*FileEntity, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*FileEntity), nil
}

// GetAll reads all stored objects
func (box *FileEntityBox) GetAll() ([]*FileEntity, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*FileEntity), nil
}

// Remove deletes a single object
func (box *FileEntityBox) Remove(object *FileEntity) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *FileEntityBox) RemoveMany(objects ...*FileEntity) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the FileEntity_ struct to create conditions.
// Keep the *FileEntityQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *FileEntityBox) Query(conditions ...objectbox.Condition) *FileEntityQuery {
	return &FileEntityQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the FileEntity_ struct to create conditions.
// Keep the *FileEntityQuery if you intend to execute the query multiple times.
func (box *FileEntityBox) QueryOrError(conditions ...objectbox.Condition) (*FileEntityQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &FileEntityQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See FileEntityAsyncBox for more information.
func (box *FileEntityBox) Async() *FileEntityAsyncBox {
	return &FileEntityAsyncBox{AsyncBox: box.Box.Async()}
}

// FileEntityAsyncBox provides asynchronous operations on FileEntity objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type FileEntityAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForFileEntity creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use FileEntityBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForFileEntity(ob *objectbox.ObjectBox, timeoutMs uint64) *FileEntityAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 2, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 2: %s" + err.Error())
	}
	return &FileEntityAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *FileEntityAsyncBox) Put(object *FileEntity) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *FileEntityAsyncBox) Insert(object *FileEntity) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *FileEntityAsyncBox) Update(object *FileEntity) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *FileEntityAsyncBox) Remove(object *FileEntity) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all FileEntity which Id is either 42 or 47:
//
// box.Query(FileEntity_.Id.In(42, 47)).Find()
type FileEntityQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *FileEntityQuery) Find() ([]*FileEntity, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*FileEntity), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *FileEntityQuery) Offset(offset uint64) *FileEntityQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *FileEntityQuery) Limit(limit uint64) *FileEntityQuery {
	query.Query.Limit(limit)
	return query
}

type nodeEntity_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var NodeEntityBinding = nodeEntity_EntityInfo{
	Entity: objectbox.Entity{
		Id: 3,
	},
	Uid: 7626999044627350868,
}

// NodeEntity_ contains type-based Property helpers to facilitate some common operations such as Queries.
var NodeEntity_ = struct {
	Id             *objectbox.PropertyUint64
	StableID       *objectbox.PropertyString
	Kind           *objectbox.PropertyString
	Name           *objectbox.PropertyString
	QualifiedName  *objectbox.PropertyString
	FilePath       *objectbox.PropertyString
	Language       *objectbox.PropertyString
	StartLine      *objectbox.PropertyInt
	EndLine        *objectbox.PropertyInt
	StartColumn    *objectbox.PropertyInt
	EndColumn      *objectbox.PropertyInt
	Signature      *objectbox.PropertyString
	ReceiverType   *objectbox.PropertyString
	ParameterCount *objectbox.PropertyInt
	ParameterTypes *objectbox.PropertyString
	ReturnType     *objectbox.PropertyString
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &NodeEntityBinding.Entity,
		},
	},
	StableID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &NodeEntityBinding.Entity,
		},
	},
	Kind: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &NodeEntityBinding.Entity,
		},
	},
	Name: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &NodeEntityBinding.Entity,
		},
	},
	QualifiedName: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &NodeEntityBinding.Entity,
		},
	},
	FilePath: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &NodeEntityBinding.Entity,
		},
	},
	Language: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &NodeEntityBinding.Entity,
		},
	},
	StartLine: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     8,
			Entity: &NodeEntityBinding.Entity,
		},
	},
	EndLine: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     9,
			Entity: &NodeEntityBinding.Entity,
		},
	},
	StartColumn: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     10,
			Entity: &NodeEntityBinding.Entity,
		},
	},
	EndColumn: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     11,
			Entity: &NodeEntityBinding.Entity,
		},
	},
	Signature: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     12,
			Entity: &NodeEntityBinding.Entity,
		},
	},
	ReceiverType: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     13,
			Entity: &NodeEntityBinding.Entity,
		},
	},
	ParameterCount: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     14,
			Entity: &NodeEntityBinding.Entity,
		},
	},
	ParameterTypes: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     15,
			Entity: &NodeEntityBinding.Entity,
		},
	},
	ReturnType: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     16,
			Entity: &NodeEntityBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (nodeEntity_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (nodeEntity_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("NodeEntity", 3, 7626999044627350868)
	model.Property("Id", 6, 1, 4740307672382472985)
	model.PropertyFlags(1)
	model.Property("StableID", 9, 2, 2492544408256570391)
	model.PropertyFlags(2080)
	model.PropertyIndex(5, 7977339421880462769)
	model.Property("Kind", 9, 3, 5132974246754897061)
	model.PropertyFlags(2048)
	model.PropertyIndex(6, 3136031450619134525)
	model.Property("Name", 9, 4, 3533172239523055308)
	model.PropertyFlags(2048)
	model.PropertyIndex(7, 772691722674290412)
	model.Property("QualifiedName", 9, 5, 1087706768695451511)
	model.PropertyFlags(2048)
	model.PropertyIndex(8, 5716309171518507146)
	model.Property("FilePath", 9, 6, 2031295220467762354)
	model.PropertyFlags(2048)
	model.PropertyIndex(9, 3661143121977444103)
	model.Property("Language", 9, 7, 4052142866617741606)
	model.PropertyFlags(2048)
	model.PropertyIndex(10, 1305682084556776024)
	model.Property("StartLine", 6, 8, 4757806515327280027)
	model.Property("EndLine", 6, 9, 3448556182795927646)
	model.Property("StartColumn", 6, 10, 200890707069712958)
	model.Property("EndColumn", 6, 11, 5894384044432350763)
	model.Property("Signature", 9, 12, 5864542766874311116)
	model.Property("ReceiverType", 9, 13, 2641842190725080668)
	model.PropertyFlags(2048)
	model.PropertyIndex(20, 967143217967356143)
	model.Property("ParameterCount", 6, 14, 7354347623517963586)
	model.Property("ParameterTypes", 9, 15, 3362153866089893544)
	model.Property("ReturnType", 9, 16, 6587390542676826859)
	model.EntityLastPropertyId(16, 6587390542676826859)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (nodeEntity_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*NodeEntity).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (nodeEntity_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*NodeEntity).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (nodeEntity_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (nodeEntity_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*NodeEntity)
	var offsetStableID = fbutils.CreateStringOffset(fbb, obj.StableID)
	var offsetKind = fbutils.CreateStringOffset(fbb, obj.Kind)
	var offsetName = fbutils.CreateStringOffset(fbb, obj.Name)
	var offsetQualifiedName = fbutils.CreateStringOffset(fbb, obj.QualifiedName)
	var offsetFilePath = fbutils.CreateStringOffset(fbb, obj.FilePath)
	var offsetLanguage = fbutils.CreateStringOffset(fbb, obj.Language)
	var offsetSignature = fbutils.CreateStringOffset(fbb, obj.Signature)
	var offsetReceiverType = fbutils.CreateStringOffset(fbb, obj.ReceiverType)
	var offsetParameterTypes = fbutils.CreateStringOffset(fbb, obj.ParameterTypes)
	var offsetReturnType = fbutils.CreateStringOffset(fbb, obj.ReturnType)

	// build the FlatBuffers object
	fbb.StartObject(16)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetStableID)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetKind)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetName)
	fbutils.SetUOffsetTSlot(fbb, 4, offsetQualifiedName)
	fbutils.SetUOffsetTSlot(fbb, 12, offsetReceiverType)
	fbutils.SetInt64Slot(fbb, 13, int64(obj.ParameterCount))
	fbutils.SetUOffsetTSlot(fbb, 14, offsetParameterTypes)
	fbutils.SetUOffsetTSlot(fbb, 15, offsetReturnType)
	fbutils.SetUOffsetTSlot(fbb, 5, offsetFilePath)
	fbutils.SetUOffsetTSlot(fbb, 6, offsetLanguage)
	fbutils.SetInt64Slot(fbb, 7, int64(obj.StartLine))
	fbutils.SetInt64Slot(fbb, 8, int64(obj.EndLine))
	fbutils.SetInt64Slot(fbb, 9, int64(obj.StartColumn))
	fbutils.SetInt64Slot(fbb, 10, int64(obj.EndColumn))
	fbutils.SetUOffsetTSlot(fbb, 11, offsetSignature)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (nodeEntity_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'NodeEntity' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &NodeEntity{
		Id:             propId,
		StableID:       fbutils.GetStringSlot(table, 6),
		Kind:           fbutils.GetStringSlot(table, 8),
		Name:           fbutils.GetStringSlot(table, 10),
		QualifiedName:  fbutils.GetStringSlot(table, 12),
		ReceiverType:   fbutils.GetStringSlot(table, 28),
		ParameterCount: fbutils.GetIntSlot(table, 30),
		ParameterTypes: fbutils.GetStringSlot(table, 32),
		ReturnType:     fbutils.GetStringSlot(table, 34),
		FilePath:       fbutils.GetStringSlot(table, 14),
		Language:       fbutils.GetStringSlot(table, 16),
		StartLine:      fbutils.GetIntSlot(table, 18),
		EndLine:        fbutils.GetIntSlot(table, 20),
		StartColumn:    fbutils.GetIntSlot(table, 22),
		EndColumn:      fbutils.GetIntSlot(table, 24),
		Signature:      fbutils.GetStringSlot(table, 26),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (nodeEntity_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*NodeEntity, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (nodeEntity_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*NodeEntity), nil)
	}
	return append(slice.([]*NodeEntity), object.(*NodeEntity))
}

// Box provides CRUD access to NodeEntity objects
type NodeEntityBox struct {
	*objectbox.Box
}

// BoxForNodeEntity opens a box of NodeEntity objects
func BoxForNodeEntity(ob *objectbox.ObjectBox) *NodeEntityBox {
	return &NodeEntityBox{
		Box: ob.InternalBox(3),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the NodeEntity.Id property on the passed object will be assigned the new ID as well.
func (box *NodeEntityBox) Put(object *NodeEntity) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the NodeEntity.Id property on the passed object will be assigned the new ID as well.
func (box *NodeEntityBox) Insert(object *NodeEntity) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *NodeEntityBox) Update(object *NodeEntity) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *NodeEntityBox) PutAsync(object *NodeEntity) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the NodeEntity.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the NodeEntity.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *NodeEntityBox) PutMany(objects []*NodeEntity) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *NodeEntityBox) Get(id uint64) (*NodeEntity, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*NodeEntity), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *NodeEntityBox) GetMany(ids ...uint64) ([]*NodeEntity, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*NodeEntity), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *NodeEntityBox) GetManyExisting(ids ...uint64) ([]*NodeEntity, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*NodeEntity), nil
}

// GetAll reads all stored objects
func (box *NodeEntityBox) GetAll() ([]*NodeEntity, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*NodeEntity), nil
}

// Remove deletes a single object
func (box *NodeEntityBox) Remove(object *NodeEntity) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *NodeEntityBox) RemoveMany(objects ...*NodeEntity) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the NodeEntity_ struct to create conditions.
// Keep the *NodeEntityQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *NodeEntityBox) Query(conditions ...objectbox.Condition) *NodeEntityQuery {
	return &NodeEntityQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the NodeEntity_ struct to create conditions.
// Keep the *NodeEntityQuery if you intend to execute the query multiple times.
func (box *NodeEntityBox) QueryOrError(conditions ...objectbox.Condition) (*NodeEntityQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &NodeEntityQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See NodeEntityAsyncBox for more information.
func (box *NodeEntityBox) Async() *NodeEntityAsyncBox {
	return &NodeEntityAsyncBox{AsyncBox: box.Box.Async()}
}

// NodeEntityAsyncBox provides asynchronous operations on NodeEntity objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type NodeEntityAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForNodeEntity creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use NodeEntityBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForNodeEntity(ob *objectbox.ObjectBox, timeoutMs uint64) *NodeEntityAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 3, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 3: %s" + err.Error())
	}
	return &NodeEntityAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *NodeEntityAsyncBox) Put(object *NodeEntity) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *NodeEntityAsyncBox) Insert(object *NodeEntity) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *NodeEntityAsyncBox) Update(object *NodeEntity) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *NodeEntityAsyncBox) Remove(object *NodeEntity) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all NodeEntity which Id is either 42 or 47:
//
// box.Query(NodeEntity_.Id.In(42, 47)).Find()
type NodeEntityQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *NodeEntityQuery) Find() ([]*NodeEntity, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*NodeEntity), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *NodeEntityQuery) Offset(offset uint64) *NodeEntityQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *NodeEntityQuery) Limit(limit uint64) *NodeEntityQuery {
	query.Query.Limit(limit)
	return query
}

type edgeEntity_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var EdgeEntityBinding = edgeEntity_EntityInfo{
	Entity: objectbox.Entity{
		Id: 4,
	},
	Uid: 4862423828518506709,
}

// EdgeEntity_ contains type-based Property helpers to facilitate some common operations such as Queries.
var EdgeEntity_ = struct {
	Id             *objectbox.PropertyUint64
	SourceStableID *objectbox.PropertyString
	TargetStableID *objectbox.PropertyString
	Kind           *objectbox.PropertyString
	FilePath       *objectbox.PropertyString
	Line           *objectbox.PropertyInt
	Column         *objectbox.PropertyInt
	Provenance     *objectbox.PropertyString
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &EdgeEntityBinding.Entity,
		},
	},
	SourceStableID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &EdgeEntityBinding.Entity,
		},
	},
	TargetStableID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &EdgeEntityBinding.Entity,
		},
	},
	Kind: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &EdgeEntityBinding.Entity,
		},
	},
	FilePath: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &EdgeEntityBinding.Entity,
		},
	},
	Line: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &EdgeEntityBinding.Entity,
		},
	},
	Column: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &EdgeEntityBinding.Entity,
		},
	},
	Provenance: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     8,
			Entity: &EdgeEntityBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (edgeEntity_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (edgeEntity_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("EdgeEntity", 4, 4862423828518506709)
	model.Property("Id", 6, 1, 5200201183198721454)
	model.PropertyFlags(1)
	model.Property("SourceStableID", 9, 2, 6879004711832604345)
	model.PropertyFlags(2048)
	model.PropertyIndex(11, 2099392463863600710)
	model.Property("TargetStableID", 9, 3, 2967104119924270555)
	model.PropertyFlags(2048)
	model.PropertyIndex(12, 9140278198054538349)
	model.Property("Kind", 9, 4, 1963848408639858949)
	model.PropertyFlags(2048)
	model.PropertyIndex(13, 1663063142446608740)
	model.Property("FilePath", 9, 5, 1181060633773048674)
	model.PropertyFlags(2048)
	model.PropertyIndex(14, 3140560180761939826)
	model.Property("Line", 6, 6, 2751853900498146644)
	model.Property("Column", 6, 7, 7980827936999242277)
	model.Property("Provenance", 9, 8, 4543557479040090025)
	model.EntityLastPropertyId(8, 4543557479040090025)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (edgeEntity_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*EdgeEntity).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (edgeEntity_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*EdgeEntity).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (edgeEntity_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (edgeEntity_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*EdgeEntity)
	var offsetSourceStableID = fbutils.CreateStringOffset(fbb, obj.SourceStableID)
	var offsetTargetStableID = fbutils.CreateStringOffset(fbb, obj.TargetStableID)
	var offsetKind = fbutils.CreateStringOffset(fbb, obj.Kind)
	var offsetFilePath = fbutils.CreateStringOffset(fbb, obj.FilePath)
	var offsetProvenance = fbutils.CreateStringOffset(fbb, obj.Provenance)

	// build the FlatBuffers object
	fbb.StartObject(8)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetSourceStableID)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetTargetStableID)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetKind)
	fbutils.SetUOffsetTSlot(fbb, 4, offsetFilePath)
	fbutils.SetInt64Slot(fbb, 5, int64(obj.Line))
	fbutils.SetInt64Slot(fbb, 6, int64(obj.Column))
	fbutils.SetUOffsetTSlot(fbb, 7, offsetProvenance)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (edgeEntity_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'EdgeEntity' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &EdgeEntity{
		Id:             propId,
		SourceStableID: fbutils.GetStringSlot(table, 6),
		TargetStableID: fbutils.GetStringSlot(table, 8),
		Kind:           fbutils.GetStringSlot(table, 10),
		FilePath:       fbutils.GetStringSlot(table, 12),
		Line:           fbutils.GetIntSlot(table, 14),
		Column:         fbutils.GetIntSlot(table, 16),
		Provenance:     fbutils.GetStringSlot(table, 18),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (edgeEntity_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*EdgeEntity, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (edgeEntity_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*EdgeEntity), nil)
	}
	return append(slice.([]*EdgeEntity), object.(*EdgeEntity))
}

// Box provides CRUD access to EdgeEntity objects
type EdgeEntityBox struct {
	*objectbox.Box
}

// BoxForEdgeEntity opens a box of EdgeEntity objects
func BoxForEdgeEntity(ob *objectbox.ObjectBox) *EdgeEntityBox {
	return &EdgeEntityBox{
		Box: ob.InternalBox(4),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the EdgeEntity.Id property on the passed object will be assigned the new ID as well.
func (box *EdgeEntityBox) Put(object *EdgeEntity) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the EdgeEntity.Id property on the passed object will be assigned the new ID as well.
func (box *EdgeEntityBox) Insert(object *EdgeEntity) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *EdgeEntityBox) Update(object *EdgeEntity) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *EdgeEntityBox) PutAsync(object *EdgeEntity) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the EdgeEntity.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the EdgeEntity.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *EdgeEntityBox) PutMany(objects []*EdgeEntity) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *EdgeEntityBox) Get(id uint64) (*EdgeEntity, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*EdgeEntity), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *EdgeEntityBox) GetMany(ids ...uint64) ([]*EdgeEntity, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*EdgeEntity), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *EdgeEntityBox) GetManyExisting(ids ...uint64) ([]*EdgeEntity, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*EdgeEntity), nil
}

// GetAll reads all stored objects
func (box *EdgeEntityBox) GetAll() ([]*EdgeEntity, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*EdgeEntity), nil
}

// Remove deletes a single object
func (box *EdgeEntityBox) Remove(object *EdgeEntity) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *EdgeEntityBox) RemoveMany(objects ...*EdgeEntity) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the EdgeEntity_ struct to create conditions.
// Keep the *EdgeEntityQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *EdgeEntityBox) Query(conditions ...objectbox.Condition) *EdgeEntityQuery {
	return &EdgeEntityQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the EdgeEntity_ struct to create conditions.
// Keep the *EdgeEntityQuery if you intend to execute the query multiple times.
func (box *EdgeEntityBox) QueryOrError(conditions ...objectbox.Condition) (*EdgeEntityQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &EdgeEntityQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See EdgeEntityAsyncBox for more information.
func (box *EdgeEntityBox) Async() *EdgeEntityAsyncBox {
	return &EdgeEntityAsyncBox{AsyncBox: box.Box.Async()}
}

// EdgeEntityAsyncBox provides asynchronous operations on EdgeEntity objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type EdgeEntityAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForEdgeEntity creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use EdgeEntityBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForEdgeEntity(ob *objectbox.ObjectBox, timeoutMs uint64) *EdgeEntityAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 4, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 4: %s" + err.Error())
	}
	return &EdgeEntityAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *EdgeEntityAsyncBox) Put(object *EdgeEntity) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *EdgeEntityAsyncBox) Insert(object *EdgeEntity) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *EdgeEntityAsyncBox) Update(object *EdgeEntity) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *EdgeEntityAsyncBox) Remove(object *EdgeEntity) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all EdgeEntity which Id is either 42 or 47:
//
// box.Query(EdgeEntity_.Id.In(42, 47)).Find()
type EdgeEntityQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *EdgeEntityQuery) Find() ([]*EdgeEntity, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*EdgeEntity), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *EdgeEntityQuery) Offset(offset uint64) *EdgeEntityQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *EdgeEntityQuery) Limit(limit uint64) *EdgeEntityQuery {
	query.Query.Limit(limit)
	return query
}

type unresolvedReferenceEntity_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var UnresolvedReferenceEntityBinding = unresolvedReferenceEntity_EntityInfo{
	Entity: objectbox.Entity{
		Id: 5,
	},
	Uid: 8009807915262133108,
}

// UnresolvedReferenceEntity_ contains type-based Property helpers to facilitate some common operations such as Queries.
var UnresolvedReferenceEntity_ = struct {
	Id            *objectbox.PropertyUint64
	FromStableID  *objectbox.PropertyString
	ReferenceName *objectbox.PropertyString
	ReferenceKind *objectbox.PropertyString
	FilePath      *objectbox.PropertyString
	Language      *objectbox.PropertyString
	Line          *objectbox.PropertyInt
	Column        *objectbox.PropertyInt
	ReceiverText  *objectbox.PropertyString
	ArgumentCount *objectbox.PropertyInt
	ArgumentTexts *objectbox.PropertyString
	ScopeStableID *objectbox.PropertyString
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &UnresolvedReferenceEntityBinding.Entity,
		},
	},
	FromStableID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &UnresolvedReferenceEntityBinding.Entity,
		},
	},
	ReferenceName: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &UnresolvedReferenceEntityBinding.Entity,
		},
	},
	ReferenceKind: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &UnresolvedReferenceEntityBinding.Entity,
		},
	},
	FilePath: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &UnresolvedReferenceEntityBinding.Entity,
		},
	},
	Language: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &UnresolvedReferenceEntityBinding.Entity,
		},
	},
	Line: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &UnresolvedReferenceEntityBinding.Entity,
		},
	},
	Column: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     8,
			Entity: &UnresolvedReferenceEntityBinding.Entity,
		},
	},
	ReceiverText: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     9,
			Entity: &UnresolvedReferenceEntityBinding.Entity,
		},
	},
	ArgumentCount: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     10,
			Entity: &UnresolvedReferenceEntityBinding.Entity,
		},
	},
	ArgumentTexts: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     11,
			Entity: &UnresolvedReferenceEntityBinding.Entity,
		},
	},
	ScopeStableID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     12,
			Entity: &UnresolvedReferenceEntityBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (unresolvedReferenceEntity_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (unresolvedReferenceEntity_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("UnresolvedReferenceEntity", 5, 8009807915262133108)
	model.Property("Id", 6, 1, 4172527558472329220)
	model.PropertyFlags(1)
	model.Property("FromStableID", 9, 2, 7322233948351692174)
	model.PropertyFlags(2048)
	model.PropertyIndex(15, 2171323865800745138)
	model.Property("ReferenceName", 9, 3, 7972036343677783478)
	model.PropertyFlags(2048)
	model.PropertyIndex(16, 2534133963459598125)
	model.Property("ReferenceKind", 9, 4, 3515345726039362762)
	model.PropertyFlags(2048)
	model.PropertyIndex(17, 4351443479712870676)
	model.Property("FilePath", 9, 5, 1521244803568825085)
	model.PropertyFlags(2048)
	model.PropertyIndex(18, 6266699770799151718)
	model.Property("Language", 9, 6, 1275514527372146217)
	model.PropertyFlags(2048)
	model.PropertyIndex(19, 8544295943047035425)
	model.Property("Line", 6, 7, 5760036363277584253)
	model.Property("Column", 6, 8, 2068640150242227716)
	model.Property("ReceiverText", 9, 9, 2744622207414599777)
	model.Property("ArgumentCount", 6, 10, 6439453596243244728)
	model.Property("ArgumentTexts", 9, 11, 5048081844580895408)
	model.Property("ScopeStableID", 9, 12, 8622643544102293813)
	model.PropertyFlags(2048)
	model.PropertyIndex(21, 8024976706042757456)
	model.EntityLastPropertyId(12, 8622643544102293813)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (unresolvedReferenceEntity_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*UnresolvedReferenceEntity).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (unresolvedReferenceEntity_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*UnresolvedReferenceEntity).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (unresolvedReferenceEntity_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (unresolvedReferenceEntity_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*UnresolvedReferenceEntity)
	var offsetFromStableID = fbutils.CreateStringOffset(fbb, obj.FromStableID)
	var offsetReferenceName = fbutils.CreateStringOffset(fbb, obj.ReferenceName)
	var offsetReferenceKind = fbutils.CreateStringOffset(fbb, obj.ReferenceKind)
	var offsetFilePath = fbutils.CreateStringOffset(fbb, obj.FilePath)
	var offsetLanguage = fbutils.CreateStringOffset(fbb, obj.Language)
	var offsetReceiverText = fbutils.CreateStringOffset(fbb, obj.ReceiverText)
	var offsetArgumentTexts = fbutils.CreateStringOffset(fbb, obj.ArgumentTexts)
	var offsetScopeStableID = fbutils.CreateStringOffset(fbb, obj.ScopeStableID)

	// build the FlatBuffers object
	fbb.StartObject(12)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetFromStableID)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetReferenceName)
	fbutils.SetUOffsetTSlot(fbb, 8, offsetReceiverText)
	fbutils.SetInt64Slot(fbb, 9, int64(obj.ArgumentCount))
	fbutils.SetUOffsetTSlot(fbb, 10, offsetArgumentTexts)
	fbutils.SetUOffsetTSlot(fbb, 11, offsetScopeStableID)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetReferenceKind)
	fbutils.SetUOffsetTSlot(fbb, 4, offsetFilePath)
	fbutils.SetUOffsetTSlot(fbb, 5, offsetLanguage)
	fbutils.SetInt64Slot(fbb, 6, int64(obj.Line))
	fbutils.SetInt64Slot(fbb, 7, int64(obj.Column))
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (unresolvedReferenceEntity_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'UnresolvedReferenceEntity' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &UnresolvedReferenceEntity{
		Id:            propId,
		FromStableID:  fbutils.GetStringSlot(table, 6),
		ReferenceName: fbutils.GetStringSlot(table, 8),
		ReceiverText:  fbutils.GetStringSlot(table, 20),
		ArgumentCount: fbutils.GetIntSlot(table, 22),
		ArgumentTexts: fbutils.GetStringSlot(table, 24),
		ScopeStableID: fbutils.GetStringSlot(table, 26),
		ReferenceKind: fbutils.GetStringSlot(table, 10),
		FilePath:      fbutils.GetStringSlot(table, 12),
		Language:      fbutils.GetStringSlot(table, 14),
		Line:          fbutils.GetIntSlot(table, 16),
		Column:        fbutils.GetIntSlot(table, 18),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (unresolvedReferenceEntity_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*UnresolvedReferenceEntity, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (unresolvedReferenceEntity_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*UnresolvedReferenceEntity), nil)
	}
	return append(slice.([]*UnresolvedReferenceEntity), object.(*UnresolvedReferenceEntity))
}

// Box provides CRUD access to UnresolvedReferenceEntity objects
type UnresolvedReferenceEntityBox struct {
	*objectbox.Box
}

// BoxForUnresolvedReferenceEntity opens a box of UnresolvedReferenceEntity objects
func BoxForUnresolvedReferenceEntity(ob *objectbox.ObjectBox) *UnresolvedReferenceEntityBox {
	return &UnresolvedReferenceEntityBox{
		Box: ob.InternalBox(5),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the UnresolvedReferenceEntity.Id property on the passed object will be assigned the new ID as well.
func (box *UnresolvedReferenceEntityBox) Put(object *UnresolvedReferenceEntity) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the UnresolvedReferenceEntity.Id property on the passed object will be assigned the new ID as well.
func (box *UnresolvedReferenceEntityBox) Insert(object *UnresolvedReferenceEntity) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *UnresolvedReferenceEntityBox) Update(object *UnresolvedReferenceEntity) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *UnresolvedReferenceEntityBox) PutAsync(object *UnresolvedReferenceEntity) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the UnresolvedReferenceEntity.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the UnresolvedReferenceEntity.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *UnresolvedReferenceEntityBox) PutMany(objects []*UnresolvedReferenceEntity) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *UnresolvedReferenceEntityBox) Get(id uint64) (*UnresolvedReferenceEntity, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*UnresolvedReferenceEntity), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *UnresolvedReferenceEntityBox) GetMany(ids ...uint64) ([]*UnresolvedReferenceEntity, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*UnresolvedReferenceEntity), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *UnresolvedReferenceEntityBox) GetManyExisting(ids ...uint64) ([]*UnresolvedReferenceEntity, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*UnresolvedReferenceEntity), nil
}

// GetAll reads all stored objects
func (box *UnresolvedReferenceEntityBox) GetAll() ([]*UnresolvedReferenceEntity, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*UnresolvedReferenceEntity), nil
}

// Remove deletes a single object
func (box *UnresolvedReferenceEntityBox) Remove(object *UnresolvedReferenceEntity) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *UnresolvedReferenceEntityBox) RemoveMany(objects ...*UnresolvedReferenceEntity) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the UnresolvedReferenceEntity_ struct to create conditions.
// Keep the *UnresolvedReferenceEntityQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *UnresolvedReferenceEntityBox) Query(conditions ...objectbox.Condition) *UnresolvedReferenceEntityQuery {
	return &UnresolvedReferenceEntityQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the UnresolvedReferenceEntity_ struct to create conditions.
// Keep the *UnresolvedReferenceEntityQuery if you intend to execute the query multiple times.
func (box *UnresolvedReferenceEntityBox) QueryOrError(conditions ...objectbox.Condition) (*UnresolvedReferenceEntityQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &UnresolvedReferenceEntityQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See UnresolvedReferenceEntityAsyncBox for more information.
func (box *UnresolvedReferenceEntityBox) Async() *UnresolvedReferenceEntityAsyncBox {
	return &UnresolvedReferenceEntityAsyncBox{AsyncBox: box.Box.Async()}
}

// UnresolvedReferenceEntityAsyncBox provides asynchronous operations on UnresolvedReferenceEntity objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type UnresolvedReferenceEntityAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForUnresolvedReferenceEntity creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use UnresolvedReferenceEntityBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForUnresolvedReferenceEntity(ob *objectbox.ObjectBox, timeoutMs uint64) *UnresolvedReferenceEntityAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 5, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 5: %s" + err.Error())
	}
	return &UnresolvedReferenceEntityAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *UnresolvedReferenceEntityAsyncBox) Put(object *UnresolvedReferenceEntity) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *UnresolvedReferenceEntityAsyncBox) Insert(object *UnresolvedReferenceEntity) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *UnresolvedReferenceEntityAsyncBox) Update(object *UnresolvedReferenceEntity) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *UnresolvedReferenceEntityAsyncBox) Remove(object *UnresolvedReferenceEntity) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all UnresolvedReferenceEntity which Id is either 42 or 47:
//
// box.Query(UnresolvedReferenceEntity_.Id.In(42, 47)).Find()
type UnresolvedReferenceEntityQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *UnresolvedReferenceEntityQuery) Find() ([]*UnresolvedReferenceEntity, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*UnresolvedReferenceEntity), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *UnresolvedReferenceEntityQuery) Offset(offset uint64) *UnresolvedReferenceEntityQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *UnresolvedReferenceEntityQuery) Limit(limit uint64) *UnresolvedReferenceEntityQuery {
	query.Query.Limit(limit)
	return query
}
