// Code generated by ObjectBox; DO NOT EDIT.

package store

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

// ObjectBoxModel declares and builds the model from all the entities in the package.
// It is usually used when setting-up ObjectBox as an argument to the Builder.Model() function.
func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()
	model.GeneratorVersion(6)

	model.RegisterBinding(MetadataEntityBinding)
	model.RegisterBinding(FileEntityBinding)
	model.RegisterBinding(NodeEntityBinding)
	model.RegisterBinding(EdgeEntityBinding)
	model.RegisterBinding(UnresolvedReferenceEntityBinding)
	model.LastEntityId(5, 8009807915262133108)
	model.LastIndexId(21, 8024976706042757456)

	return model
}
